name: cicd-build
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  checks:
    name: Check on ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-darwin
            os: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            system = ${{ matrix.system }}
      - name: Run Flake Check
        run: nix flake check --system ${{ matrix.system }}
