name: cicd-lint
on: [push, pull_request, workflow_dispatch]
jobs:
  checks-fmt:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: nix build .#checks.x86_64-linux.treefmt
      - run: nix build .#checks.aarch64-darwin.treefmt
  check-statix:
    name: check statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
  check-deadnix:
    name: check deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
        with:
          commit_message: "chore: remove dead code"
